# Generated by Django 5.1.1 on 2024-09-10 13:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='complaint_files'), upload_to='complaints/')),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
