# Generated by Django 5.1.1 on 2024-09-10 13:49

import django.core.files.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_complaint_delete_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='PNR',
            field=models.TextField(default=6541658987, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='mobile',
            field=models.TextField(default=8685646521, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='complaint_files'), upload_to='complaints/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
    ]
