# Generated by Django 5.1.1 on 2024-09-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_complaint_pnr_complaint_date_complaint_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
