# Generated by Django 5.1.1 on 2024-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_complaint_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sentiment',
            field=models.TextField(blank=True),
        ),
    ]
