# Generated by Django 5.1.1 on 2024-09-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_complaint_analysis_complaint_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
